name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Kích hoạt khi push vào nhánh main
  pull_request:
    branches: [ "main" ]  # Kích hoạt khi có pull request vào main

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên máy ảo Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Lấy mã nguồn từ repository

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Sử dụng Node.js phiên bản 20

      - name: Install dependencies
        run: npm install      # Cài đặt dependencies

      - name: Run tests
        run: npm test        # Chạy kiểm thử (định nghĩa trong package.json)

  deploy:
    needs: test  # Chỉ chạy sau khi job test thành công
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Chỉ deploy khi push vào main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --production  # Chỉ cài dependencies production

      - name: Deploy to Heroku (Ví dụ)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Khóa API lưu trong Secrets
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          npm install -g heroku
          heroku login --api-key $HEROKU_API_KEY
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
